[project]
name = "walletbackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi-mail>=1.6.5",
    "fastapi[all]>=0.141.1",
    "greenlet>=3.5.5",
    "itsdangerous>=2.2.0",
    "passlib[argon2]>=1.7.4",
    "phonenumbers>=9.0.36",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
    "redis>=8.1.0",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.52",
]
