"""increasing phone number length

Revision ID: 69439a7fe8a7
Revises:
Create Date: 2026-08-12 16:46:18.110736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69439a7fe8a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_event_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_repayment_id', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_loans_user_id', table_name='loans')
    op.drop_table('loans', cascade=True)
    op.drop_index('ix_transactions_loan_id', table_name='transactions')
    op.drop_index('ix_transactions_repayment_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_repayments_loan_id', table_name='repayments')
    op.drop_index('ix_repayments_user_id', table_name='repayments')
    op.drop_table('repayments')
    op.drop_index('ix_ledgers_loan_id', table_name='ledgers')
    op.drop_index('ix_ledgers_repayment_id', table_name='ledgers')
    op.drop_index('ix_ledgers_transaction_id', table_name='ledgers')
    op.drop_index('ix_ledgers_user_id', table_name='ledgers')
    op.drop_table('ledgers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledgers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repayment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entry_type', postgresql.ENUM('disbursement', 'repayment', 'interest_accrual', 'fee', 'adjustment', 'write_off', name='ledger_entry_type_enum'), server_default=sa.text("'disbursement'::ledger_entry_type_enum"), autoincrement=False, nullable=False),
    sa.Column('account', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_ledgers_created_by_users'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name='fk_ledgers_loan_id_loans'),
    sa.ForeignKeyConstraint(['repayment_id'], ['repayments.id'], name='fk_ledgers_repayment_id_repayments'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_ledgers_transaction_id_transactions'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_ledgers_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_ledgers')
    )
    op.create_index('ix_ledgers_user_id', 'ledgers', ['user_id'], unique=False)
    op.create_index('ix_ledgers_transaction_id', 'ledgers', ['transaction_id'], unique=False)
    op.create_index('ix_ledgers_repayment_id', 'ledgers', ['repayment_id'], unique=False)
    op.create_index('ix_ledgers_loan_id', 'ledgers', ['loan_id'], unique=False)
    op.create_table('repayments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', 'cancelled', name='repayment_status_enum'), server_default=sa.text("'pending'::repayment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('gateway_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name='fk_repayments_loan_id_loans'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_repayments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_repayments'),
    sa.UniqueConstraint('gateway_reference', name='uq_repayments_gateway_reference', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_repayments_user_id', 'repayments', ['user_id'], unique=False)
    op.create_index('ix_repayments_loan_id', 'repayments', ['loan_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('customer', 'admin', 'staf', name='role_enum'), server_default=sa.text("'customer'::role_enum"), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repayment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gateway_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', name='transaction_status_enum'), server_default=sa.text("'pending'::transaction_status_enum"), autoincrement=False, nullable=False),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name='fk_transactions_loan_id_loans'),
    sa.ForeignKeyConstraint(['repayment_id'], ['repayments.id'], name='fk_transactions_repayment_id_repayments'),
    sa.PrimaryKeyConstraint('id', name='pk_transactions')
    )
    op.create_index('ix_transactions_repayment_id', 'transactions', ['repayment_id'], unique=False)
    op.create_index('ix_transactions_loan_id', 'transactions', ['loan_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('principal', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'active', 'paid_off', 'defaulted', 'written_off', name='loan_status_enum'), server_default=sa.text("'pending'::loan_status_enum"), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('balance >= 0::numeric', name='ck_loans_ck_loans_balance_non_negative'),
    sa.CheckConstraint('interest_rate >= 0::numeric', name='ck_loans_ck_loans_interest_rate_non_negative'),
    sa.CheckConstraint('principal > 0::numeric', name='ck_loans_ck_loans_principal_postive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_loans_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_loans'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_loans_user_id', 'loans', ['user_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gate_way', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('repayment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['loans.id'], name='fk_webhook_events_event_id_loans'),
    sa.ForeignKeyConstraint(['repayment_id'], ['repayments.id'], name='fk_webhook_events_repayment_id_repayments'),
    sa.PrimaryKeyConstraint('id', name='pk_webhook_events')
    )
    op.create_index('ix_webhook_events_repayment_id', 'webhook_events', ['repayment_id'], unique=False)
    op.create_index('ix_webhook_events_event_id', 'webhook_events', ['event_id'], unique=False)
    # ### end Alembic commands ###
