"""changed repayment status

Revision ID: 7cdc8617fa14
Revises: 
Create Date: 2026-10-04 15:49:55.048432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cdc8617fa14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledgers_loan_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_repayment_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_user_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_repayments_loan_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_user_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_repayment_schedules_due_date'), table_name='repayment_schedules')
    op.drop_index(op.f('ix_repayment_schedules_loan_id'), table_name='repayment_schedules')
    op.drop_index(op.f('ix_repayment_schedules_user_id'), table_name='repayment_schedules')
    op.drop_table('repayment_schedules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_webhook_events_repayment_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gate_way', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('repayment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repayment_id'], ['repayments.id'], name=op.f('fk_webhook_events_repayment_id_repayments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_webhook_events_event_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_webhook_events_repayment_id'), 'webhook_events', ['repayment_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('principal', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('savings_balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('repayment_frequency', postgresql.ENUM('daily', 'weekly', 'monthly', name='repayment_frequncy_enum'), server_default=sa.text("'monthly'::repayment_frequncy_enum"), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('installment', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'active', 'paid_off', 'defaulted', 'written_off', name='loan_status_enum'), server_default=sa.text("'active'::loan_status_enum"), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('balance >= 0::numeric', name=op.f('ck_loans_ck_loans_balance_non_negative')),
    sa.CheckConstraint('interest_rate >= 0::numeric', name=op.f('ck_loans_ck_loans_interest_rate_non_negative')),
    sa.CheckConstraint('principal > 0::numeric', name=op.f('ck_loans_ck_loans_principal_postive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('customer', 'admin', 'staf', name='role_enum'), server_default=sa.text("'customer'::role_enum"), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('repayment_schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('installment_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount_due', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', 'cancelled', name='repayment_status_enum'), server_default=sa.text("'pending'::repayment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_repayment_schedules_loan_id_loans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_repayment_schedules_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repayment_schedules'))
    )
    op.create_index(op.f('ix_repayment_schedules_user_id'), 'repayment_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_repayment_schedules_loan_id'), 'repayment_schedules', ['loan_id'], unique=False)
    op.create_index(op.f('ix_repayment_schedules_due_date'), 'repayment_schedules', ['due_date'], unique=False)
    op.create_table('repayments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', 'cancelled', name='repayment_status_enum'), server_default=sa.text("'pending'::repayment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('gateway_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_repayments_loan_id_loans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_repayments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repayments')),
    sa.UniqueConstraint('gateway_reference', name=op.f('uq_repayments_gateway_reference'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_repayments_user_id'), 'repayments', ['user_id'], unique=False)
    op.create_index(op.f('ix_repayments_loan_id'), 'repayments', ['loan_id'], unique=False)
    op.create_table('ledgers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repayment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entry_type', postgresql.ENUM('disbursement', 'repayment', 'savings_credit', 'interest_accrual', 'fee', 'adjustment', 'write_off', name='ledger_entry_type_enum'), server_default=sa.text("'disbursement'::ledger_entry_type_enum"), autoincrement=False, nullable=False),
    sa.Column('account', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledgers_created_by_users')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_ledgers_loan_id_loans')),
    sa.ForeignKeyConstraint(['repayment_id'], ['repayments.id'], name=op.f('fk_ledgers_repayment_id_repayments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledgers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledgers'))
    )
    op.create_index(op.f('ix_ledgers_user_id'), 'ledgers', ['user_id'], unique=False)
    op.create_index(op.f('ix_ledgers_repayment_id'), 'ledgers', ['repayment_id'], unique=False)
    op.create_index(op.f('ix_ledgers_loan_id'), 'ledgers', ['loan_id'], unique=False)
    # ### end Alembic commands ###
